#!/bin/bash

# Setup script for Game Deployment Project
# Generates ALL configuration files based on user input
# Integrates lessons from 25+ local Docker integration gotchas

set -e

echo "=================================================="
echo "      Game Deployment Setup Wizard"
echo "=================================================="

# ─── 1. Get User Input ───

read -p "Enter Admin Node Public IP: " ADMIN_IP
read -p "Enter Game Node Public IP: " GAME_IP
read -p "Enter Admin Node Internal IP [leave empty if same network/local]: " ADMIN_INTERNAL_IP
read -p "Enter Game Node Internal IP [leave empty if same network/local]: " GAME_INTERNAL_IP
read -s -p "Enter Database Password [leave empty for random]: " DB_PASS
echo ""
read -s -p "Enter Redis Password [leave empty for random]: " REDIS_PASS
echo ""

# Default internal IPs to public IPs if not provided
ADMIN_INTERNAL_IP="${ADMIN_INTERNAL_IP:-$ADMIN_IP}"
GAME_INTERNAL_IP="${GAME_INTERNAL_IP:-$GAME_IP}"

if [ -z "$DB_PASS" ]; then
    DB_PASS=$(openssl rand -hex 12)
    echo "Generated DB Password: $DB_PASS"
fi

if [ -z "$REDIS_PASS" ]; then
    REDIS_PASS=$(openssl rand -hex 12)
    echo "Generated Redis Password: $REDIS_PASS"
fi

# ─── 2. SSL Certificate ───

echo ""
echo "--- SSL Certificate Setup ---"
read -p "SSL fullchain.pem path [leave empty for self-signed]: " SSL_CERT

if [ -z "$SSL_CERT" ]; then
    echo "Generating self-signed SSL certificates..."
    mkdir -p admin-node/certs game-node/certs

    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout admin-node/certs/privkey.pem \
        -out admin-node/certs/fullchain.pem \
        -subj "/CN=${ADMIN_IP}" 2>/dev/null

    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout game-node/certs/privkey.pem \
        -out game-node/certs/fullchain.pem \
        -subj "/CN=${GAME_IP}" 2>/dev/null

    echo "Self-signed certificates generated."
else
    read -p "SSL privkey.pem path: " SSL_KEY
    mkdir -p admin-node/certs game-node/certs
    cp "$SSL_CERT" admin-node/certs/fullchain.pem
    cp "$SSL_KEY" admin-node/certs/privkey.pem
    cp "$SSL_CERT" game-node/certs/fullchain.pem
    cp "$SSL_KEY" game-node/certs/privkey.pem
    echo "SSL certificates copied."
fi

# ─── 3. Create Directories ───

mkdir -p admin-node/{scripts,db-init,configs,certs}
mkdir -p game-node/{configs,db-init,certs,client-dist}

# ─── 4. Generate .env Files ───

echo "Generating admin-node/.env..."
cat > admin-node/.env <<EOF
# Admin Node Environment Variables (generated by setup.sh)
POSTGRES_PASSWORD=${DB_PASS}
REDIS_PASSWORD=${REDIS_PASS}
GAME_NODE_IP=${GAME_IP}
ADMIN_NODE_IP=${ADMIN_IP}
# Internal IPs for cross-node server-to-server HTTP (avoids TLS issues with self-signed certs)
GAME_INTERNAL_IP=${GAME_INTERNAL_IP}
ADMIN_INTERNAL_IP=${ADMIN_INTERNAL_IP}
EOF

echo "Generating game-node/.env..."
cat > game-node/.env <<EOF
# Game Node Environment Variables (generated by setup.sh)
POSTGRES_PASSWORD=${DB_PASS}
REDIS_PASSWORD=${REDIS_PASS}
ADMIN_NODE_IP=${ADMIN_IP}
ADMIN_INTERNAL_IP=${ADMIN_INTERNAL_IP}
EOF

# ─── 5. Generate Backend config.yml ───

echo "Generating admin-node/configs/config.yml..."
cat > admin-node/configs/config.yml <<EOF
name: "platform"
data_dir: "./data-log/"
shutdown_grace_sec: 5

app:
  env: "release"
  addr: 9986
  acc_manage_header: "M7NJpSXxh"
  acc_normal_header: "aikDg57I1"
  check_header: false
  use_multipoint: false
  update_redis_data: true
  load_front: false
  load_swagger: false
  load_db_migration: true
  load_api_channel: true
  load_record_channel: true
  load_casino_channel: true
  load_backend_channel: true
  load_job_scheduler: true

jwt:
  encrypt_string: "#gFn7QSEs5TC9W29B\$Gx"
  issuer: "dcc"
  expire_time_min: 10080

captcha:
  key_length: 6
  img_width: 400
  img_height: 90
  gc_limit_number: 10240
  ExpiredSec: 60

database:
  driver_name: "postgres"
  default_db_idx: 0
  conn_info:
    - "host=postgres port=5432 user=postgres dbname=dcc_game password=${DB_PASS} sslmode=disable"
  migrate_source_url: "file://db/migrations"

logger:
  stdout: false
  level: "info"
  file: "./data-log/logfile.log"
  rotation: true
  max_size: 128

redis:
  address: "redis:6379"
  password: "${REDIS_PASS}"
  db_index:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
EOF

# ─── 6. Generate OrderService config ───

echo "Generating admin-node/configs/orderservice.yml..."
cat > admin-node/configs/orderservice.yml <<EOF
name: "platform"
data_dir: "./data-log/"
shutdown_grace_sec: 5

app:
  env: "release"
  addr: 9988
  acc_manage_header: "M7NJpSXxh"
  acc_normal_header: "aikDg57I1"
  check_header: false
  use_multipoint: false
  load_front: false
  load_swagger: false
  load_db_migration: true
  load_api_channel: false
  load_record_channel: true
  load_backend_channel: false
  load_job_scheduler: false

jwt:
  encrypt_string: "#gFn7QSEs5TC9W29B\$Gx"
  issuer: "dcc"
  expire_time_min: 10080

captcha:
  key_length: 6
  img_width: 400
  img_height: 90
  gc_limit_number: 10240
  ExpiredSec: 60

database:
  driver_name: "postgres"
  default_db_idx: 0
  conn_info:
    - "host=postgres port=5432 user=postgres dbname=dcc_order password=${DB_PASS} sslmode=disable"
    - "host=postgres port=5432 user=postgres dbname=dcc_game password=${DB_PASS} sslmode=disable"
  migrate_source_url: "file://db/migrations"

logger:
  stdout: false
  level: "info"
  file: "./data-log/logfile.log"
  rotation: true
  max_size: 128

redis:
  address: "redis:6379"
  password: "${REDIS_PASS}"
  db_index:
    - 0
    - 1
    - 2
    - 3
    - 4
EOF

# ─── 7. Generate ChatService config ───

echo "Generating admin-node/configs/chatservice.yml..."
cat > admin-node/configs/chatservice.yml <<EOF
name: "chatservice"
data_dir: "./data-log/"
shutdown_grace_sec: 5

app:
  env: "release"
  addr: 8896
  use_multipoint: false
  load_front: false
  load_swagger: false

logger:
  stdout: false
  level: "info"
  file: "./data-log/logfile.log"
  rotation: true
  max_size: 128

socket:
  server_key: "defaultkey"
  port: 8896
  address: ""
  single_socket: true

database:
  driver_name: "postgres"
  default_db_idx: 0
  conn_info:
    - "host=postgres port=5432 user=postgres dbname=dcc_chat password=${DB_PASS} sslmode=disable"
EOF

# ─── 8. Generate MonitorService config ───

echo "Generating admin-node/configs/monitorservice.yml..."
cat > admin-node/configs/monitorservice.yml <<EOF
name: "monitorservice"
data_dir: "./data-log/"
shutdown_grace_sec: 5

app:
  env: "release"
  addr: 17782
  use_multipoint: false
  load_front: false
  load_swagger: false
  is_verify_captcha: true

logger:
  stdout: false
  level: "info"
  file: "./data-log/logfile.log"
  rotation: true
  max_size: 128

socket:
  server_key: "defaultkey"
  port: 17783
  address: ""
  single_socket: true

jwt:
  encrypt_string: "#oHBda8jidas32R3G\$Op"
  issuer: "monitorservice"
  expire_time_min: 10080

captcha:
  key_length: 6
  img_width: 400
  img_height: 90
  gc_limit_number: 10240
  ExpiredSec: 3600

database:
  driver_name: "postgres"
  default_db_idx: 0
  conn_info:
    - "host=postgres port=5432 user=postgres dbname=monitor password=${DB_PASS} sslmode=disable"
EOF

# ─── 9. Generate GameHub.conf (HTTPS for SettlePlatform) ───

echo "Generating game-node/configs/GameHub.conf..."
cat > game-node/configs/GameHub.conf <<EOF
{
    "Base": {
        "Version": "1.0.0",
        "DebugMode": false,
        "CloudType": "CLIENT_DEV",
        "HttpAddr": "0.0.0.0:9643",
        "Platform": "DEV",
        "ServerID": 1,
        "LogLevel": 7
    },
    "Serverinfo": {
        "WSAddr": "0.0.0.0:10101",
        "TCPAddr": "0.0.0.0:10201",
        "CertFile": "",
        "KeyFile": "",
        "MaxConnNum": 1000,
        "ConsolePort": 3565
    },
    "Database": {
        "Name": "dayon_demo",
        "Addr": "postgres",
        "Port": 5432,
        "Account": "postgres",
        "Passwd": "${DB_PASS}"
    },
    "Redis": {
        "Uri": "redis://:${REDIS_PASS}@redis:6379",
        "Passwd": "${REDIS_PASS}",
        "Db": 2,
        "ExpireEx": 300
    },
    "TLS": {
        "Enable": false,
        "KeyFile": "",
        "CertFile": ""
    },
    "Jobqueue": {
        "Jobqueue": {
            "BufferedJobs": 100,
            "Workers": 5
        },
        "JobWorker": {
            "BufferedJobs": 100,
            "Workers": 3
        }
    },
    "SettlePlatform": {
        "LOCAL": "http://${ADMIN_INTERNAL_IP}:9986/",
        "DEV": "http://${ADMIN_INTERNAL_IP}:9986/",
        "QA": "",
        "ETE": "",
        "PRO": ""
    },
    "Log": {
        "multifile": {
            "prefix": "gamehub_pro.",
            "daily": true,
            "separate": ["error"]
        }
    },
    "Settings": {
        "BetGame": "OFF",
        "tgrobot": "",
        "JackPot": "OFF"
    }
}
EOF

# ─── 10. Generate Game Client config.json (wss:// via nginx proxy) ───

echo "Generating game-node/configs/game-client-config.json..."
cat > game-node/configs/game-client-config.json <<EOF
{
    "ServerUrl": "wss://${GAME_IP}/ws",
    "WaitWS": 1.1,
    "UsingDebugTool": false,
    "canLog": false
}
EOF

# ─── 11. Generate update_server_info.sql ───

echo "Generating admin-node/scripts/update_server_info.sql..."
cat > admin-node/scripts/update_server_info.sql <<EOF
-- Auto-generated by setup.sh
-- Updates server_info for HTTPS reverse proxy deployment

-- dev01: GameHub connection (Backend → GameHub via game-node nginx)
UPDATE server_info SET
    ip = '${GAME_IP}',
    addresses = '{"notification": "https://${GAME_IP}/gamehub/"}',
    update_time = now(),
    is_enabled = true
WHERE code = 'dev01';

-- chat: browser-facing (via admin nginx HTTPS proxy)
UPDATE server_info SET
    ip = '${ADMIN_IP}',
    addresses = jsonb_set(jsonb_set(addresses, '{domain}', '"${ADMIN_IP}"'), '{scheme}', '"https"')
WHERE code = 'chat';

-- api: browser-facing (via admin nginx HTTPS proxy)
UPDATE server_info SET
    ip = '${ADMIN_IP}',
    addresses = jsonb_set(jsonb_set(addresses, '{domain}', '"${ADMIN_IP}"'), '{scheme}', '"https"')
WHERE code = 'api';

-- monitor: browser-facing (via admin nginx HTTPS proxy)
UPDATE server_info SET
    ip = '${ADMIN_IP}',
    addresses = jsonb_set(jsonb_set(addresses, '{domain}', '"${ADMIN_IP}"'), '{scheme}', '"https"')
WHERE code = 'monitor';
EOF

# ─── 12. Generate update_game_data.sql ───

echo "Generating admin-node/scripts/update_game_data.sql..."
cat > admin-node/scripts/update_game_data.sql <<EOF
-- Auto-generated by setup.sh
-- Updates game data, agent whitelists, and storage settings

-- Fix game.h5_link (game client entry URL) — HTTPS
UPDATE game SET h5_link = 'https://${GAME_IP}' WHERE server_info_code = 'dev01';
UPDATE game SET h5_link = 'https://${GAME_IP}' WHERE id IN (0, 3003);

-- Agent IP whitelist (allow all IPs for deployment)
UPDATE agent SET ip_whitelist = '[{"info":"deploy","creator":"admin","ip_address":"*","create_time":0}]'::jsonb;
UPDATE agent SET api_ip_whitelist = '[{"info":"deploy","creator":"admin","ip_address":"*","create_time":0}]'::jsonb
WHERE top_agent_id <> -1;

-- Reset GameKillDiveInfoReset
UPDATE storage SET value = '{"flag": true, "update_time": 0}' WHERE key = 'GameKillDiveInfoReset';
EOF

# ─── 13. Copy DCC Tools schema ───

DCCTOOLS_SCHEMA="../後台/測試client(同花順)/dcctools/dump-dcc-202511082114.sql"
if [ -f "$DCCTOOLS_SCHEMA" ]; then
    echo "Copying DCC Tools schema..."
    cp "$DCCTOOLS_SCHEMA" admin-node/db-init/dcctools-schema.sql
else
    echo "WARNING: DCC Tools schema not found at $DCCTOOLS_SCHEMA"
    echo "         You need to manually copy it to admin-node/db-init/dcctools-schema.sql"
fi

# ─── 14. Copy Game SQL init files ───

GAME_SQL_DIR="../遊戲服務器/deployments/gamehub/sql"
if [ -d "$GAME_SQL_DIR" ]; then
    echo "Copying game SQL init files..."
    # Fix varchar(12) → varchar(50) for game_code column (pyrtreasureslot = 15 chars)
    sed 's/varchar(12)/varchar(50)/g' "$GAME_SQL_DIR/gamelist.sql" > game-node/db-init/gamelist.sql
    sed 's/varchar(12)/varchar(50)/g' "$GAME_SQL_DIR/gameinfo.sql" > game-node/db-init/gameinfo.sql
    cp "$GAME_SQL_DIR/lobbyinfo.sql" game-node/db-init/lobbyinfo.sql
else
    echo "WARNING: Game SQL directory not found at $GAME_SQL_DIR"
    echo "         You need to manually copy gamelist.sql, gameinfo.sql, lobbyinfo.sql to game-node/db-init/"
fi

# ─── Done ───

echo ""
echo "=================================================="
echo "Configuration Complete!"
echo ""
echo "Files generated:"
echo "  admin-node/"
echo "    .env                              (DB/Redis passwords, IPs)"
echo "    certs/fullchain.pem, privkey.pem  (SSL certificates)"
echo "    configs/config.yml                (Backend config)"
echo "    configs/orderservice.yml          (OrderService config)"
echo "    configs/chatservice.yml           (ChatService config)"
echo "    configs/monitorservice.yml        (MonitorService config)"
echo "    db-init/init-extra-dbs.sql        (Extra DB creation)"
echo "    db-init/dcctools-schema.sql       (DCC Tools MySQL schema)"
echo "    db-init/dcctools-init.sql         (DCC Tools MySQL fixes)"
echo "    scripts/update_server_info.sql    (Server info SQL)"
echo "    scripts/update_game_data.sql      (Game data SQL)"
echo ""
echo "  game-node/"
echo "    .env                              (DB/Redis passwords, IPs)"
echo "    certs/fullchain.pem, privkey.pem  (SSL certificates)"
echo "    configs/GameHub.conf              (GameHub config)"
echo "    configs/game-client-config.json   (Plinko client config)"
echo "    db-init/gamelist.sql              (Game list init)"
echo "    db-init/gameinfo.sql              (Game info init)"
echo "    db-init/lobbyinfo.sql             (Lobby info init)"
echo ""
echo "Next Steps:"
echo "  1. Run 'bash squash_db.sh' to clean up DB migrations (recommended)"
echo "  2. Run 'bash gcloud_firewall.sh' to see firewall commands"
echo "  3. Copy game client files to game-node/client-dist/"
echo "  4. Upload ENTIRE project to both servers (build needs source code)"
echo "  5. Start Game Node FIRST: cd game-node && docker compose up -d --build"
echo "  6. Then Admin Node: cd admin-node && docker compose up -d --build"
echo "  7. Verify: https://${ADMIN_IP}/manager  https://${GAME_IP}/"
echo "=================================================="
