#!/bin/bash

# Database Migration Squashing Tool
# Consolidates 300+ migration files into a single clean_init.sql
# Usage: bash squash_db.sh

set -e

MIGRATION_DIR="../後台/platform-ete/backend/db/migrations"
OUTPUT_FILE="admin-node/db-init/clean_init.sql"
TEMP_CONTAINER="temp_pg_squash"
DB_NAME="dcc_game"
DB_USER="postgres"
DB_PASS="password"

echo "=================================================="
echo "      Database Squashing Tool"
echo "=================================================="

# 1. Cleanup previous run
echo "Cleaning up any previous containers..."
docker rm -f $TEMP_CONTAINER 2>/dev/null || true

# 2. Start Temporary Postgres
echo "Starting temporary Postgres container..."
docker run --name $TEMP_CONTAINER -e POSTGRES_PASSWORD=$DB_PASS -d postgres:14-alpine

echo "Waiting for Postgres to be ready..."
sleep 5
until docker exec $TEMP_CONTAINER pg_isready -U $DB_USER; do
  echo "Waiting for Postgres..."
  sleep 2
done

# 3. Create Database
echo "Creating database $DB_NAME..."
docker exec -e PGPASSWORD=$DB_PASS $TEMP_CONTAINER createdb -U $DB_USER $DB_NAME

# 4. Run Migrations
echo "Running existing migrations..."
# We use a simple loop because we don't have golang-migrate installed in the temp container
# Mounting the migration dir
# Note: This assumes we are running in a shell where we can mount paths.
# If not, we copy files. COPY is safer.

docker cp "$MIGRATION_DIR" $TEMP_CONTAINER:/migrations

# Execute SQL files in order
# Using a complex command inside sh to sort and run
docker exec -e PGPASSWORD=$DB_PASS $TEMP_CONTAINER sh -c '
    cd /migrations
    for f in $(ls *.up.sql | sort); do
        echo "Running $f..."
        psql -U postgres -d dcc_game -f "$f" > /dev/null 2>&1
    done
'

echo "All migrations applied."

# 5. Export Schema (Structure)
echo "Exporting Schema..."
docker exec -e PGPASSWORD=$DB_PASS $TEMP_CONTAINER pg_dump -U $DB_USER -d $DB_NAME \
    --section=pre-data --section=post-data \
    --no-owner --no-acl > schema.sql

# 6. Export Seed Data (Specific Tables Only)
echo "Exporting Seed Data..."
# List of tables to KEEP data for
TABLES_TO_KEEP=(
    "admin_user"
    "agent"
    "agent_permission"
    "permission_list"
    "game"
    "game_room"
    "agent_game"
    "agent_game_room"
    "server_info"
    "exchange_data"
    "storage"
)

DATA_ARGS=""
for t in "${TABLES_TO_KEEP[@]}"; do
    DATA_ARGS="$DATA_ARGS --table=public.$t"
done

docker exec -e PGPASSWORD=$DB_PASS $TEMP_CONTAINER pg_dump -U $DB_USER -d $DB_NAME \
    --data-only --column-inserts \
    $DATA_ARGS \
    > data.sql

# 7. Combine
echo "Combining into $OUTPUT_FILE..."
echo "-- Clean Init SQL generated by squash_db.sh at $(date)" > $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
cat schema.sql >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
cat data.sql >> $OUTPUT_FILE

# 8. Clean up
rm schema.sql data.sql
docker rm -f $TEMP_CONTAINER

echo "=================================================="
echo "Success! Clean init SQL saved to $OUTPUT_FILE"
echo "Size: $(du -h $OUTPUT_FILE | cut -f1)"
echo "=================================================="
